// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-3LXdVZC78NS8n1NywjfaSDzcEFzMuA',
    appId: '1:517112843884:android:32b10fe05e4ecf21f29249',
    messagingSenderId: '517112843884',
    projectId: 'dw-todolist',
    storageBucket: 'dw-todolist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmIvNYOOpUqO9wVPuyy16FCYe7lv_FS9I',
    appId: '1:517112843884:ios:d1411ea016477c86f29249',
    messagingSenderId: '517112843884',
    projectId: 'dw-todolist',
    storageBucket: 'dw-todolist.appspot.com',
    iosClientId: '517112843884-6j1bkfd60mj21il5klgdlqbapc7m9elh.apps.googleusercontent.com',
    iosBundleId: 'com.polymorph.todolist',
  );
}
